<?php

/*
 * State constants
 */
const STATE_PLAYER_TURN = 2;
const STATE_INCREMENT_ACTION = 4;
const STATE_WAR_SUPPORT = 6;
const STATE_REVOLT_SUPPORT = 7;
const STATE_SELECT_WAR_LEADER = 9;
const STATE_BUILD_MONUMENT = 10;
const STATE_WAR_PROGRESS = 11;
const STATE_REVOLT_PROGRESS = 12;
const STATE_PICK_TREASURE = 13;
const STATE_FINAL_SCORING = 14;
const STATE_MULTI_MONUMENT = 15;
const STATE_END_TURN_CONFIRM = 16;
const STATE_NEXT_PLAYER = 17;
const STATE_BUILD_CIVILIZATION_BUILDING = 18;
const STATE_MULTI_WONDER = 19;
const STATE_WONDER_SCORE = 20;
const STATE_END_GAME = 99;

/*
 * Game Constants
 */

const WAR_NO_WAR = 0;
const WAR_ATTACKER_SUPPORT = 1;
const WAR_DEFENDER_SUPPORT = 2;
const WAR_START = 3;
const NO_ID = 999;
const DB_UNDO_YES = 1;
const AWAITING_SELECTION = 0;
const PICK_SAME_PLAYER = 1;
const PICK_DIFFERENT_PLAYER = 2;
const OPEN_SCORING = 2;
const ENGLISH_VARIANT = 2;
const WONDER_VARIANT = 2;
const CIVILIZATION_VARIANT = 2;
